[tool.bumper]
current_version = "1.0.1"

[[tool.bumper.files]]
file = "./pyproject.toml"
search = 'version = "{current_version}"'

[[tool.bumper.files]]
file = "./README.md"
search = "matplotlib-window/{current_version}"
